name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.0
          cache: true

      - name: Install dependencies
        run: |
          cd perfect
          flutter pub get

      - name: Run Flutter tests
        run: |
          cd perfect
          flutter test

      - name: Build Web App (Optional)
        run: |
          cd perfect
          flutter build web

      - name: Upload Web Build (Optional)
        uses: actions/upload-artifact@v4  # UPDATED TO v4
        with:
          name: flutter-web-build
          path: perfect/build/web

      - name: Build Android APK (Optional)
        run: |
          cd perfect
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4  # UPDATED TO v4
        with:
          name: release-apk
          path: perfect/build/app/outputs/flutter-apk/app-release.apk
